services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb_data:/data/db

  todo-api:
    container_name: todo-api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:5000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
    

volumes:
  mongodb_data:
    external: false 